import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "./components/nav";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="pl">
      <body className='font-text text-my-green bg-my-beige leading-relaxed'>
        <div className="grid h-screen grid-rows-[auto,1fr]">
          <Nav />
          <main className="overflow-y-scroll">{children}</main>
        </div>
      </body>
      </html>
    </ClerkProvider>
  );
}
